---
title: "Capstone Project Proposal"
author: "Jennifer Klein"
date: "11/15/2017"
output: html_document
---

# Springboard Capstone Project  
#### **Podcasts: The Next Big Thing in Media?**

Podcasts have emerged as the trendy new medium in media. But there’s still so little we know about the audience listening to this nascent form of entertainment. We know how many times a podcast is downloaded, but we don’t know audience demographics, how many people are skipping through ads, etc. That’s all about to change with  Apple’s recent announcement that it is finally going to provide comprehensive analytics about listener behavior to podcast publishers. I propose using data to seek out emerging trends in the genre.

### **1. What is the problem you want to solve?**  AND
### **2. Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?**

I would like to prove that certain topics are more appealing to the podcast listener and therefore publishers can tailor their content around these subjects to attract more listeners, garner more downloads and, ultimately, attract more adverisers and increase their revenue. 

### **3. What data are you going to use for this? How will you acquire this data?**

Since I don't want my sample to be too disparate, I will stick to the top 50 or so podcasts listed in the Soctiety & Culture section on Apple Podcasts. I also don't want to get bogged down in too much information, so I will only use the podcast name, episode title, date, running time and, most importantly, episode description and popularity rating in my set. I'll use a self-created dataset, since similar datasets on Data World or Kaggle are either few and far between or otherwise unusable for this project.
 + Apple's API is not the most user friendly, though, so I will scrape a different podcast hosting site, Stitcher, to obtain the data for my dataset and use Apple Podcasts for their popularity rating, the most important information I need for what I'm hoping to accomplish.  

### **4. In brief, outline your approach to solving this problem (knowing that this might change later).**

I will use the popularity rating of episodes in a single podcast and see if there's some relationship between popularity and keywords in the episode description. I will obtain the data as described in Answer #3. I also hope to use text mining, text analytics, clustering and NLP to help me draw appropriate conclusions from my data.   

###   **5. What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.**

The deliverables for this project will be submitted on github. This will include code that I use to analyze the data, key findings, word clouds and summarizations. I hope to tell a compelling story with my data - since my background is in marketing and book publishing, storytelling and gaining key insights are what drew me into data science in the first place!